### ISSUE TITLE
Feral Druid Bear abilities are causing the incorrect amount of threat (most of them at least)

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1191] opened 2019-04-28 15:12 UTC
**Description:**

Lacerate - spell 33745 is apply less threat then it should
Demoralizing Roar - Spell 26998 is applying the correct amount of threat but is spreading it over all target effected instead of applying the flat threat amount to each target

**Current behavior:**

Cast Lacerate on a target, using .debug threat on PTR threat returned was 92.5 when the expected threat should have been 423.11

Cast Demoralizing roar on a target, using .debug it returned the correct amount of threat against a single target (60.9) but when cast against 3 mobs at once each mob only returns 20 threat each. 

**Expected behaviour:**

https://www.wowhead.com/forums&topic=7507 - As per this

Bear Form and Dire Bear Form multiply all base threat generated by 1.3. 5/5 Feral Instinct increases this multiplier to 1.45.
Lacerate does 285 base threat plus 20% of all damage it deals.
Demoralizing Roar generates base threat equal to 42.

**Steps to reproduce the problem:**

1. Cast Lacerate on a target then use .debug threat - notice it do also less threat then it should
2. Cast Demo roar against multiple targets, use .debug threat - notice the threat is split among all targets hit instead of it applying the base threat to all targets

Rev. 11100

**Comment by Kaziner** [comment] 2019-04-29 13:31
https://web.archive.org/web/20080223152408/http://forums.worldofwarcraft.com:80/thread.html?topicId=75381044&sid=1&pageNo=1#2

Demo roar and Demo shout do split threat in TBC - not a bug

https://wow.gamepedia.com/Demoralizing_Roar

**Comment by kelno** [comment] 2019-04-29 15:16
As a note, Omen files agrees on Lacerate doing: 285 + 20% threat

**Comment by Cheelout** [comment] 2019-05-04 06:50
Have tested again on the PTR each application of lacerate is applying around 430~ threat

**Comment by kelno** [comment] 2019-05-04 11:42
This contradicts the initial post here, but anyway we have an incorrect value in either case

**Comment by Cheelout** [comment] 2019-05-08 02:27
@kelno Threat looks much better at the moment. More in line with where it should be. I think this is resolved.

**Comment by kelno** [comment] 2019-05-09 19:53
I can see lacerate threat is correct in database, dunno how you got 430.
I'll close for now.

**Comment by Kaziner** [comment] 2019-05-11 02:38
![5-11-2019 12-35-59 PM](https://user-images.githubusercontent.com/45530324/57564076-953eb600-73e9-11e9-88f5-883bc0682a25.png)

Re-tested on PTR; giving 91.6 threat (back to what it was prior to fix) rev 11191

**Comment by kelno** [comment] 2019-05-11 12:47
Seems to be some interaction with talents, we can only reproduce it on some characters but not others. We're investigating it!

**Comment by kelno** [comment] 2019-05-11 13:46
Okay, fixed with 11230

**Closed** 2019-05-11 13:45 UTC
Labels: doublechecked
