### ISSUE TITLE
cleave range issue

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#634] opened 2019-02-17 00:58 UTC
**Description:**
the warrior spell cleave is behaving incorrectly, the range for it hitting another mob seems to be very small
**Current behaviour:**
use cleave on 2 mobs that are more than seemingly 2 yards apart, cleave will not hit the second mob
**Expected behaviour:**
use cleave on 2 mobs less than around 8 yards apart, cleave should hit about that distance, no less than 5 yards the spell doesn't specify.

**Steps to reproduce the problem:**
1. find 2 mobs
2. position them on top of each other and cleave, should hit both
3. spread them further apart, cleave will not hit them at the correct ranges

**Comment by Jerrythemagicdog** [comment] 2019-02-17 06:55
Okay, so https://wow.gamepedia.com/Cleave mentions of the Radius being 8 yards. That means 4 yards one way, and 4 yards the other way in a frontal cone (unless we, for some reason, assume it should be 8+8 which amounts to 16 yards in a frontal cone, haha. )
I did some testing and I really don't see the issue, seems to be going over that 4 yard side limit anyway:
https://streamable.com/3uxne

**Comment by oj449** [comment] 2019-02-17 07:15
The retail ability is a different one now, the old cleave should be coded
as 5 yards from you, to intiate the attack, then from that target 5 or so
yards target range to hit the nearest other target ally as well, but that
is meant to be 5 from the middle out i am pretty sure, or it basically can
only hit overlapping targets which should not be the case.

**Comment by oj449** [comment] 2019-02-17 08:28
also i think you have radius and diameter mixed up, diameter is the full length across a circle, radius is center out.

**Comment by Jerrythemagicdog** [comment] 2019-02-17 09:03
Let's not argue semantics. Either provide actual reproduce steps where it happened, and how to reproduce reliably or we're going to be stuck here going back and forth forever.

**Comment by kelno** [comment] 2019-02-17 09:04
It's indeed 5 yards radius https://wow.gamepedia.com/index.php?title=Cleave&oldid=1431966.

It seems to is not directly related to a range issue since it happens it specific cases only, seeing the video by Jerry. It's possibly related to creature movement, it would really be useful if you could provide a video of it happening so that we try to reproduce and find the exact problem here.

**Comment by oj449** [comment] 2019-02-17 12:53
Would you accept a comparison video between vanilla server cleave and the
beta cleave? The wording wasn't changed and i'm pretty sure no mechanics
for it were, so i can do a bunch of hits showing where cleave isn't hitting
something very close to another mob that seems to be in range and also have
a vid of same range vanilla hitting it.

**Comment by artieau** [comment] 2019-03-28 12:21
@oj449 yes please add your details

**Comment by oj449** [comment] 2019-04-02 10:31
well, i can't do the vanilla video thing as the server closed, but i have found a video of cleave hitting a target about 8 yards away, https://youtu.be/fPQRqe_ycHo?t=344

**Comment by kelno** [comment] 2019-04-03 04:52
I wouldn't accept another private server video as a source on this. Retail video like this are welcome though.

**Comment by artieau** [comment] 2019-04-19 15:10
Closing until we have any other information, appears to be correct

**Closed by artieau** 2019-04-19 15:10 UTC
Labels: question, spells
