### ISSUE TITLE
Some HoT's being unable to be refreshed due to "A more powerful spell already active"

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#1222] opened 2019-05-04 12:56 UTC
**Description:**

Several spells including Lifebloom, Rejuvenation of Druid and Renew from Priests cannot be refreshed on a target.  This is not affecting Regrowth however and seems to only be spells with ONLY heal over time effects.

**Current behaviour:**

When cast on a target, you cannot refresh them until they expire.

**Expected behaviour:**

You should be able to refresh your own by casting it again.

**Steps to reproduce the problem:**

1. Cast Rejuvenation, Lifebloom or Renew on a target.
2. Try to refresh it by casting the spell again
3. Receive "A more powerful spell is already active." error message
4. Post bug

 **rev. hash/commit:** 	

 CHANGEME	
Do a `.server info` in game and copy/screenshot the first line.  	
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`
![image](https://user-images.githubusercontent.com/43313533/57179304-d4d44200-6ebf-11e9-9989-1070807924c6.png)

**Comment by giveusmezpls** [comment] 2019-05-04 12:57
This is a duplicate of https://github.com/thebarrensissues/Issues/issues/1223

**Comment by kelno** [comment] 2019-05-04 13:18
You mean #1223 is a duplicate of #1222

**Comment by giveusmezpls** [comment] 2019-05-04 13:22
This is also applying to deadly poison stacks perhaps other poisons as well.
Deadly Poison is not stacking, other poisons are not refreshing.

**Comment by kelno** [comment] 2019-05-04 13:44
Fixed with 11152

**Closed** 2019-05-04 13:44 UTC
