### ISSUE TITLE
[#196] [Quest] Bloody Vengeance (10250)

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#485] opened 2019-02-14 18:01 UTC
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 10:20 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/196_

----

Current Behaviour:
NPC Urtrak (19862) who is summoned by blowing horn item (28651) appears but when he dies player does not get quest credit for killing the mob

Expected Behaviour:
Killing Urtrak (19862) should credit quest and mark quest completed for hand in.

Tried summoning and killing 2 times

**Comment by kelno** [comment] 2019-02-14 18:01
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 10:22 GMT_

----

Was able to complete the quest and get kill credit by .damage 10000 command and killing him instantly before the friendly NPC 19864 Vengeful Unyielding Captain x6 showed up to assist with killing Urtrak. Other attempts when they were participating in the fight stopped the kill credit.

**Comment by Tamosheik** [comment] 2019-04-06 09:40
Duplicate of #973

**Closed by Tamosheik** 2019-04-06 09:40 UTC
Labels: doublechecked
