### ISSUE TITLE
[QUEST] Neltharaku's Tale

### ISSUE THREAD

**Issue by cursedbitcoin** [thebarrensissues/Issues#1018] opened 2019-04-05 02:22 UTC
**Description:**

When listening to Neltharaku's story, I can't finish the dialogue.

**Current behaviour:**

Converse with Neltharaku, final interaction 'I have battled many beasts, dragon. I will help you.' cannot be selected.

**Expected behaviour:**

Should be able to select the interaction and finish the quest.

Neltharaku's Tale - Quest ID #10814
Neltharaku - NPC #21657

**rev. hash/commit:** 
![revhash1](https://user-images.githubusercontent.com/48847635/55599944-ce11bc80-57a5-11e9-98e1-a52ee59279d0.png)

**Comment by Tamosheik** [comment] 2019-04-06 08:29
Duplicate of #962

**Closed by Tamosheik** 2019-04-06 08:29 UTC
