### ISSUE TITLE
[Quest] What Book? I Don't See Any Book. (10231)

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#993] opened 2019-04-03 04:29 UTC
**Description:**

Quest not completable

**Current behaviour:**

Select gossip option in "Dirty" Larry after talking to him but he is not attackable, just goes back to neutral and not attackable

**Expected behaviour:**

Should be able to give him the the beat down he deserves

**Steps to reproduce the problem:**

**rev. hash/commit:** 

10843

**Comment by dinkletron** [comment] 2019-04-03 05:47
Can confirm, his two sidekicks become hostile and are killable, but Larry stays neutral.

**Comment by Tamosheik** [comment] 2019-04-04 03:06
Duplicate of Issue #678. Please use the search function before posting new issues.

**Closed by Tamosheik** 2019-04-04 03:06 UTC
