### ISSUE TITLE
[quest] Neltharaku's Tale

### ISSUE THREAD

**Issue by cryptochiefy** [thebarrensissues/Issues#995] opened 2019-04-03 06:19 UTC
When going through the text dialog getting upto the text "i have battled many beasts, dragon, i WIll help you. 

Clicking this does nothing and means you cant complete the quest. screen shot attached
![DRAGON](https://user-images.githubusercontent.com/42995820/55457119-49e7f980-562c-11e9-94ef-a25c85253be5.png)
.

**Comment by plutonium447** [comment] 2019-04-03 14:07
Duplicate of https://github.com/thebarrensissues/Issues/issues/962

**Closed by plutonium447** 2019-04-03 14:07 UTC
