### ISSUE TITLE
Spell casts/buffs expiring too early

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#835] opened 2019-03-23 01:36 UTC
**Description:**

Buffs are not lasting their entire duration.

**Current behaviour:**

Example: Ice Barrier(Rank 4) [13033] Is expiring with 8 seconds left to go.
Example: Frost Ward (Rank 4) [10177] Is expiring with 6 seconds left to go.

**Expected behaviour:**

Example Ice Barrier(Rank 4 )  [13033] Should last it's full duration of 1 min
Example: Frost Ward (Rank 4) [10177] Should last it's full duration of 30 seconds.

**Steps to reproduce the problem:**

CHANGEME
1. Intermittent problem, does not appear until playing for some time. Unsure what trigger is.
2. Buffs suddenly begin to start expiring early. Seems to be percentage based? 

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54859995-bb3dc780-4d63-11e9-8ab9-d0fae0310f60.png)

**Comment by qoth** [comment] 2019-03-23 01:52
Hearthing appears to fix it temporarily. Zoning does not.

**Comment by Jerrythemagicdog** [comment] 2019-03-23 17:38
Can't reproduce locally or on EU ptr, same issue as before.

**Comment by qoth** [comment] 2019-03-24 01:03
https://www.youtube.com/watch?v=huLis--rMC4&feature=youtu.be

**Comment by qoth** [comment] 2019-03-24 01:04
Note that 2 of the mobs break out of nova early, before blizzard hits them.

**Comment by qoth** [comment] 2019-03-24 01:18
Additionally whenever this bug does occur, mobs that are slowed by spells like blizzard, appear to 'jump forward' when they die.

**Comment by qoth** [comment] 2019-03-24 01:31
https://youtu.be/fgm6CRGpMsk

Another video from my perspective. Shows the cast bar finishing early and Ice barrier buff expiring early.

Also note the final mob I kill speeding up as it dies.

**Comment by qoth** [comment] 2019-03-24 11:03
I can also regularly replicate this, just still don't know what the trigger is. Happens almost immediately when farming DM:E

**Comment by emorelix** [comment] 2019-03-27 11:41
sap(spell=11297)/blind(spell=2094) in pvp seem to break a bit early too in rev 10762

**Comment by kelno** [comment] 2019-04-03 05:26
I've applied a possible temporary fix to this, we'll see how that works. Active with next reboot.

**Comment by Killabean** [comment] 2019-04-04 01:48
I have experienced multiple symptoms consistent with erratic timing.  This includes #812 Random fall damage, Frost Nova & Polymorph expiring early, NPCs "jumping" position, Frostbolt flight animation speed varying.

**Comment by kelno** [comment] 2019-04-15 09:31
A temporary fix has been applied for a while.
I still need to write a proper fix to this.

**Comment by kelno** [comment] 2019-04-16 07:36
-> https://github.com/thebarrensissues/Issues/issues/1115

**Closed by kelno** 2019-04-16 07:36 UTC
Labels: core, doublechecked, gamebreaking, high priority
