### ISSUE TITLE
[Quest] Administering the salve

### ISSUE THREAD

**Issue by imtrollingu** [thebarrensissues/Issues#1077] opened 2019-04-11 21:35 UTC
**Description:**

Quest actions happen but don't count.
Quest ID http://db.hellfire-tbc.com/?quest=9447

**Current behaviour:**

When you use the quest item on the NPC the action happens and the NPC reacts but it's not counted in the quest log making it impossible to complete the quest.
http://db.hellfire-tbc.com/?item=23394

**Expected behaviour:**

Use the quest item, NPC is cured and it is counted in the quest log

**Steps to reproduce the problem:**

Step 1: Disable Addons
Step 2: Deleted WDB folder
Step 3: Tried on multiple different NPCS

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Jerrythemagicdog** [comment] 2019-04-11 22:12
duplicate of https://github.com/thebarrensissues/Issues/issues/1059

**Closed by Jerrythemagicdog** 2019-04-11 22:12 UTC
