### ISSUE TITLE
 [Arcane Instability] gives 33% spell crit chance

### ISSUE THREAD

**Issue by vblongneck** [thebarrensissues/Issues#850] opened 2019-03-23 18:42 UTC
**Description:**

talent provides 30% too much spell critical chance.

**Current behaviour:**

The arcane tree talent Arcane Instability (spell=15058) gives 33% total spell crit chance. 1/3 is 31%, 2/3 is 32%, 3/3 is 33%.

**Expected behaviour:**

to provide 3% total crit chance

**Steps to reproduce the problem:**

1. put 3 points into arcane instability
2. blow everything up
3. tell everyone how much you love arcane
4. find out its bugged
5. reeeeeeeeee

**rev. hash/commit:** 
![ree2](https://user-images.githubusercontent.com/48788674/54870211-6db27080-4dde-11e9-8a43-45b8e6ab11fa.png)

**Comment by Jerrythemagicdog** [comment] 2019-03-23 19:58
I did some testing, this situation only happens when the Mage has **both** Arcane Potency (31573 for rank 3) and Arcane Instability (15060 for rank 3.) 
Arcane Potency should only add the critical strike chance during Clearcasting (http://tbc.cavernoftime.com/spell=31573)

**Comment by kelno** [comment] 2019-03-24 06:49
Then the issue should be:
" [Arcane Potency] gives 30% spell crit chance at all time"
But I'll try to fix it just now, no need to rewrite

**Comment by kelno** [comment] 2019-03-24 08:33
Might be fixed now but not sure. I can't reproduce the bug.

**Comment by Cheelout** [comment] 2019-03-24 21:04
The proc chance from Arcane Potency is applying to crit rating per skill point. Vb has a video.

**Comment by vblongneck** [comment] 2019-03-24 21:09
https://cdn.discordapp.com/attachments/547690593132871690/559482509839302668/Desktop_2019.03.25_-_05.02.37.02_Trim.mp4

https://cdn.discordapp.com/attachments/547690593132871690/559483316147847207/Desktop_2019.03.25_-_05.06.04.03_Trim.mp4

**Comment by kelno** [comment] 2019-03-25 22:16
Fixed with 10758

**Closed** 2019-03-25 22:15 UTC
Labels: core, doublechecked, high priority, spells
