### ISSUE TITLE
[QUEST] Dimensius the All-Devouring (10439)

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#1026] opened 2019-04-05 08:22 UTC
**Description:**
Captain Saeed (NPC: 20985) needs to be interacted with for the completion of the quest. When interacted with a small event is supposed to begin where he and his soldiers follow a path into the building that Dimensius is housed. At this point you interact with Saeed again and this makes it possible for Demensius to spawn. Currently the event involves the guards just running back and forward and therefore makes the quest impossible to complete. 

**Current behaviour:**
Event is not able to complete and therefore the mob required cannot be spawned. 

**Expected behaviour:**
The expected event can be seen in the following video: https://www.youtube.com/watch?v=AZc9pdhKqPk

**Steps to reproduce the problem:**
1. Will need to complete the two pre-quests: On Nethery Wings (quest=10438) and Recipe for destruction (quest=10437)
2. Start the quest "Dimensius the All-Devouring" (quest=10439)
3. Talk to Captain Saeed (NPC: 20985) and proceed through dialogue options
4. Watch him and his soldiers.

**Comment by Jerrythemagicdog** [comment] 2019-04-05 12:37
duplicate of https://github.com/thebarrensissues/Issues/issues/967

**Closed by Jerrythemagicdog** 2019-04-05 12:37 UTC
