### ISSUE TITLE
Heal over time spells cant be cast on the same target if the target is affected by this spell.

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1223] opened 2019-05-04 12:57 UTC
**Description:**

Renew (priest), rejuv, lifebloom etc. cannot be cast on a target who is affected by the spell already. The message is "a more powerful spell is active".

**Current behaviour:**

![image](https://user-images.githubusercontent.com/49624667/57179303-d3a31500-6ebf-11e9-881c-fade1ad71e71.png)

**Expected behaviour:**

It is expected you can overwrite these buffs with the same version / more powerful version, also lifebloom should stack.

**Steps to reproduce the problem:**

1. cast the spell on a target
2, cast the spell on a ta... nvm a more powerful spell is active.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57179316-f5040100-6ebf-11e9-9466-9ae78ccddd5c.png)

**Comment by zemfi** [comment] 2019-05-04 13:01
gamebreaking regression issue, cant stack multiple stacks of lifebloom, pretty much nerfs resto druids. Can comfirm the above.

**Comment by giveusmezpls** [comment] 2019-05-04 13:09
This is also applying to deadly poison stacks perhaps other poisons as well.

**Comment by kelno** [comment] 2019-05-04 13:18
Duplicate of https://github.com/thebarrensissues/Issues/issues/1222

**Closed by kelno** 2019-05-04 13:18 UTC
Labels: doublechecked, gamebreaking, high priority, spells
