### ISSUE TITLE
[#278] Someone else's hard work pays off doesn't spawn.

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#547] opened 2019-02-14 23:01 UTC
<a href="https://github.com/Desparto"><img src="https://avatars0.githubusercontent.com/u/26176852?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Desparto](https://github.com/Desparto)**
_Thursday Feb 07, 2019 at 12:05 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/278_

----

**Current behaviour:**

This quest is supposed to spawn in Mana tombs after completing Quest Safety is job one. It doesn't. Nothing happens.

**Expected behaviour:**

Quest should spawn once previous quest is handed in.

**Steps to reproduce the problem:**

1. Hand in Safety is job one quest in mana tombs.
2. Someone else's hard work pays off should be available to pick up (ethereal should appear and offer)

https://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off
https://www.wowhead.com/quest=10216/safety-is-job-one - pre quest

**rev. hash/commit:** 

Revision 10392

**Comment by Tamosheik** [comment] 2019-04-06 09:39
Duplicate of issue #677

**Closed by Tamosheik** 2019-04-06 09:39 UTC
Labels: doublechecked
