### ISSUE TITLE
Some NPCs will fly to attack you when on flying mount

### ISSUE THREAD

**Issue by cursedbitcoin** [thebarrensissues/Issues#1020] opened 2019-04-05 02:55 UTC
**Description:**

Some NPCs (for example, Rocknail Flayers and Demon Hunter Initiates), instead of disengaging when flying in mid air, will fly to attack.

**Current behaviour:**

The NPC will 'swim' up to you whilst mounted and flying to attack. If you fly far enough away, you will leave combat.

**Expected behaviour:**

These NPCs should stay on the ground.

**Steps to reproduce the problem:**

Demon Hunter Initiate NPC #21180
Rocknail Flayer NPC #21477

**rev. hash/commit:** 

![flying DH](https://user-images.githubusercontent.com/48847635/55601024-6316b480-57aa-11e9-8e3b-fcd2c70530cc.png)
![revhash2](https://user-images.githubusercontent.com/48847635/55601026-65790e80-57aa-11e9-855e-811b14c8f7a3.png)

**Comment by kelno** [comment] 2019-04-16 06:58
To dev:
They don't have the flight flag, probably not a database issue.

**Comment by kelno** [comment] 2019-04-16 07:00
Can you make a video of this? I can't reproduce this.

**Comment by artieau** [comment] 2019-04-19 15:01
I cant make videos, but just tested myself and the mobs DO fly up and follow you.
Nailon server rev 11025

**Comment by hufsa** [comment] 2019-04-23 15:07
Reproduced. Testing with spawnID: 70814 Entry: 19792 in shadowmoon valley.

**Please note:**
If the creature is not supposed to be able to fly, they should evade instantly when you (the player) leave the ground. Also, they shouldn't engage if you're not truly on the ground.

![2](https://user-images.githubusercontent.com/1609919/56591988-11fc2280-65ea-11e9-9466-087c479e13f5.png)
![1](https://user-images.githubusercontent.com/1609919/56592006-19233080-65ea-11e9-9792-f212894b1437.png)

**Comment by zemfi** [comment] 2019-04-29 08:12
Can confirm this is happening, was able to reproduce this with various npc's in shadowmoon valley.

Heres a video:

https://streamable.com/6yoim

.rev 11098

**Comment by kelno** [comment] 2019-04-29 20:22
Thanks

**Comment by zemfi** [comment] 2019-05-05 11:14
This seems to be happening globally now (or its has always been), actually kindof fun pulling mobs around a bit. Heres one in netherstorm:

![nether_float](https://user-images.githubusercontent.com/46832429/57193047-9b144180-6f7a-11e9-8bc8-cdb9ee44723f.png)

**Comment by kelno** [comment] 2019-05-15 13:20
Fixed with 11264

**Closed by kelno** 2019-05-15 13:20 UTC
Labels: doublechecked, gamebreaking
