### ISSUE TITLE
Pickpocket removing me from stealth (without resist)

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#928] opened 2019-03-30 00:54 UTC
**Description:**

Stealth aura removed from me when i pickpocket a mob, maybe 30% of the time.

**Current behaviour:**

Pickpocketing a mob seems to remove me from stealth 30% of the time and be unsuccessful.
This is not a resist, as i am not put in combat with the mob. This is confirmed by sapping a mob then pickpocketing and stealth being removed without a resist notification and not being in combat.

**Expected behaviour:**

Pickpocket should either be successful or resist and put u in combat. Stealth should not be removed until hit. 

**Steps to reproduce the problem:**

1. Enter stealth.
2. Sap mob (optional)
3. Pickpocket mob from behind
4 30% of the time you wil be removed from stealth but not put in combat and not from a resist.

**rev. hash/commit:** 

(NOTE: This bug happens on mobs even 10 levels lower then me. but recently tested on mobs in hellfire)

STEALTH RANK 4 spell=1787

PICK POCKET spell=921

tested on mobs [npc=16966]

![WoWScrnShot_033019_115131](https://user-images.githubusercontent.com/47015256/55268895-437f1800-52e2-11e9-972d-b3217569a9d2.jpg)

**Comment by kelno** [comment] 2019-06-04 12:59
Can't reproduce, maybe it's fixed?
Someone else also tells me he can't reproduce it anymore.
Closing for now.

**Closed by kelno** 2019-06-04 12:59 UTC
