### ISSUE TITLE
[Rogue] Deadly Throw can proc Ruthlessness

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1129] opened 2019-04-17 18:04 UTC
**Description:**
Deadly Throw (26679) can proc Ruthlessness talent (14161) which can lead to endless Deadly Throw. It should not be able to proc Ruthlessness. 

**Expected behaviour:**

Deadly Throw shouldn't have a chance to proc Ruthlessness.
Source: https://wowwiki.fandom.com/wiki/Ruthlessness_(rogue_talent)
Not very related but slightly relevant: https://github.com/thebarrensissues/Issues/issues/498

**rev. hash/commit:** 	

10993

**Comment by cryptochiefy** [comment] 2019-05-11 00:06
Br0ken pllz fix

**Comment by SUN-Leekie** [comment] 2019-05-12 02:06
Fixed in 11247.

**Closed** 2019-05-12 02:06 UTC
Labels: doublechecked, spells

**Comment by cryptochiefy** [comment] 2019-05-12 06:18
its not fixed yet

**Comment by kelno** [comment] 2019-05-17 17:56
Seems to be for us, can you tell us how to reproduce?
