### ISSUE TITLE
[Quest] HELP!

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#951] opened 2019-03-31 09:21 UTC
**Description:**

Quest not working

**Current behaviour:**

Can accept the quest fine and get the key drop. But freeing the mob Corki from the cage does not give completion.

**Expected behaviour:**

Should allow you to hand in and get the next step.

**Steps to reproduce the problem:**

CHANGEME
1. Accept quest HELP!
2. Kill ogres to get key
3. Open cage

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55287285-1cac0900-53ea-11e9-8ece-2186aa245fef.png)

**Comment by Tamosheik** [comment] 2019-04-04 15:34
Duplicate of Issue #940

**Closed by Tamosheik** 2019-04-04 15:34 UTC
