### ISSUE TITLE
Murmur Heroic HP

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1187] opened 2019-04-28 03:10 UTC
**Description:**

Murmur in Heroic mode is currently at 100%hp

**Current behaviour:**

Murmur has 100% hp in Heroic mode.

**Expected behaviour:**

Murmur should have 40% HP and should RESET to 40% HP

**Steps to reproduce the problem:**

CHANGEME
1. Do Heroic Shadow Labs
2. Look at Murmur and note his HP

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/35262513/56857989-cf07c980-69b2-11e9-9570-e6a7721a0f61.png)

**Comment by SUN-Leekie** [comment] 2019-04-28 23:54
Duplicate of #1137 ?

**Comment by giveusmezpls** [comment] 2019-05-11 17:37
Yes this is a duplicate post of #1137

**Closed** 2019-05-11 18:01 UTC
